import = [
	# uncomment the flavour you want below:
	# "~/.config/alacritty/themes/catppuccin-latte.toml"
	# "~/.config/alacritty/themes/catppuccin-frappe.toml"
	# "~/.config/alacritty/themes/catppuccin-macchiato.toml"
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

live_config_reload = true

[window]
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.7
blur = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "On"}
unfocused_hollow = true
thickness = 0.15

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS NF", style = "Bold" }
size = 16
builtin_box_drawing = true
